Repository IBM/watson-assistant-workbench, pull requests merged in 2018-10, with the labels that each got.

#167 Fix reverse order of imported nodes
  scripts/dialog_xml2json.py
Labels: Priority: high, XML, bug

#164 Convert string to unicode in intent name check
  scripts/wawCommons.py
Labels: Priority: medium, XML

#169 Add documentation for localization
  doc/WAW_dialog_doc.md
  example/en_app/dialogs/chitchat.xml
Labels: Priority: medium, XML

#170 fix for script not exporting pattern entities as patterns but synonyms
  scripts/entities_csv2json.py
Labels: Priority: medium, XML, customer request

#148 Travis CI: Add flake8 tests to find undefined names
  .travis.yml
Labels: CI, Priority: high, customer request, discussion
