Repository IBM/watson-assistant-workbench, pull requests merged in 2018-08, with the labels that each got.

#71 Minor formatting proposals
  scripts.md
Labels: Priority: low, documentation

#131 Skip calling artifactory if no api key is provided
  ci/artifactory-cleanup.sh
  ci/artifactory-deploy.sh
Labels: CI

#70 Minor fixes (proposals)
  doc/Examples_T2C_XML_JSON.md
Labels: Priority: low, documentation

#69 Minor fixes
  doc/T2C_doc.md
Labels: Priority: low, documentation

#39 Fix title formatting
  doc/T2C_doc.md
Labels: Priority: low, documentation

#1 Fix missing imports: copy, sys, etc.
  scripts/cfgCommons.py
  scripts/clean_generated.py
  scripts/dialog_xml2json.py
Labels: Priority: medium

#13 Add intents and entities format documentation
  .travis.yml
  README.md
  doc/Examples_T2C_XML_JSON.md
  doc/T2C_doc.md
  doc/WAW_entities_doc.md
  doc/WAW_intents_doc.md
  scripts/cfgCommons.py
  scripts/clean_generated.py
  scripts/dialog_xml2json.py
Labels: Priority: high, documentation

#134 [#49] add requirements file
  .travis.yml
  README.md
  requirements.txt
Labels: Priority: high, documentation

#68 Add Python 3.6 to testing in allow_failures mode
  .travis.yml
Labels: Priority: medium, testing

#140 I99 digression
  data_spec/dialog_schema.xml
  doc/WAW_dialog_doc.txt
  example/en_app/dialogs/chitchat.xml
  scripts/dialog_xml2json.py
  tests/data/dialog/chitchat.xml
Labels: Priority: high, XML, customer request, enhancement
