Repository IBM/watson-assistant-workbench, pull requests merged in 2018-09, with the labels that each got.

#132 Added utf8 support to some scripts
  scripts/dialog_xml2json.py
  scripts/entities_csv2json.py
  scripts/workspace_compose.py
Labels: Priority: high, customer request

#152 [#130] Import nodes to specific position
  scripts/dialog_xml2json.py
Labels: Priority: medium, XML, customer request, enhancement

#154 [#153] formatting entity doc
  doc/WAW_entities_doc.md
Labels: Priority: low, documentation
