Repository IBM/watson-assistant-workbench, pull requests merged in 2019-02, with the labels that each got.

#215 Add openpyxl version to requirements
  requirements.txt
Labels: CI, Priority: high, T2C, bug, customer request

#212 Add build.cfg to doc
  scripts.md
Labels: Priority: low, customer request, documentation

#208 Add dialog comparison
  requirements.txt
  scripts/compare_dialogs.py
Labels: Priority: high, XML, customer request, testing

#216 Added action->credentials as optional in the XML schema definition.
  data_spec/dialog_schema.xml
Labels: Priority: medium, XML, customer request

#205 Fix empty key error
  scripts/dialog_json2xml.py
Labels: Priority: high, XML, bug, customer request

#219 Add support for metadata
  doc/WAW_dialog_doc.txt
Labels: Priority: high, XML, customer request

#218 Skills fixes
  data_spec/dialog_schema.xml
  scripts/dialog_json2xml.py
  scripts/dialog_xml2json.py
  tests/data/dialog/E_EN_anything_else.xml
  tests/data/dialog/E_EN_welcome.xml
  tests/data/dialog/chitchat.xml
Labels: Priority: high, XML, bug, customer request

#227 Fix duplicated entities
  scripts/entities_csv2json.py
Labels: CI, Priority: high, XML, customer request

#220 Deploy by name
  ci/travis.sh
  scripts/wawCommons.py
  scripts/workspace_deploy.py
  scripts/workspace_test.py
Labels: CI, Priority: high, customer request
