Repository IBM/watson-assistant-workbench, pull requests merged in 2019-03, with the labels that each got.

#235 Add unit tests
  .travis.yml
  README.md
  ci/travis.sh
  ci/unit_tests/wawCommons/getFilesAtPath_test.py
  requirements_dev.txt
Labels: CI, Priority: high, enhancement, testing

#41 t2c intent and entity value list block fix
  .gitignore
  ci/travis.sh
  scripts/IntentData.py
  scripts/NodeData.py
  scripts/XLSXHandler.py
  scripts/XMLHandler.py
  scripts/clean_generated.py
  scripts/dialog_xml2json.py
  scripts/entities_csv2json.py
  scripts/workspace_deploy.py
  tests/data/xls/cond_x_test.xlsx
Labels: Priority: high, T2C

#242 I223 files pattern matching
  ci/unit_tests/wawCommons/absoluteFilePaths_test.py
  ci/unit_tests/wawCommons/getFilesAtPath_data/directory1/file1.test
  ci/unit_tests/wawCommons/getFilesAtPath_data/directory1/fileA.ext
  ci/unit_tests/wawCommons/getFilesAtPath_data/directory2/file2.test
  ci/unit_tests/wawCommons/getFilesAtPath_test.py
  scripts/wawCommons.py
Labels: CI, Priority: medium, documentation, enhancement, testing

#233 Workspace include json
  .gitignore
  ci/unit_tests/workspace_addjson/includeJson_test.py
  ci/unit_tests/workspace_addjson/main_data/jsonToAdd.json
  ci/unit_tests/workspace_addjson/main_data/jsonToAdd_array.json
  ci/unit_tests/workspace_addjson/main_data/workspace.json
  ci/unit_tests/workspace_addjson/main_data/workspace_result.json
  ci/unit_tests/workspace_addjson/main_data/workspace_result_array.json
  ci/unit_tests/workspace_addjson/main_test.py
  scripts.md
  scripts/update_all.py
  scripts/workspace_addjson.py
Labels: Priority: high, XML, customer request, enhancement

#252 [#76] Change all prints in scripts to proper logging
  scripts/DialogData.py
  scripts/EntityData.py
  scripts/IntentData.py
  scripts/NodeData.py
  scripts/XLSXHandler.py
  scripts/XMLHandler.py
  scripts/cfgCommons.py
  scripts/clean_generated.py
  scripts/compare_dialogs.py
  scripts/dialog_code2text.py
  scripts/dialog_json2xml.py
  scripts/dialog_text2code.py
  scripts/dialog_xls2xml.py
  scripts/dialog_xml2json.py
  scripts/entities_csv2json.py
  scripts/entities_csv2nlu.py
  scripts/entities_json2csv.py
  scripts/evaluate_tests.py
  scripts/functions_deploy.py
  scripts/intents_csv2json.py
  scripts/intents_csv2nlu.py
  scripts/intents_json2csv.py
  scripts/logging_config.ini
  scripts/update_all.py
  scripts/wawCommons.py
  scripts/workspace_addjson.py
  scripts/workspace_compose.py
  scripts/workspace_decompose.py
  scripts/workspace_delete.py
  scripts/workspace_deploy.py
  scripts/workspace_test.py
Labels: Priority: high

#248 [#240] added support for cloud functions that are written in scripted…
  ci/test_utils.py
  ci/unit_tests/functions_deploy/__init__.py
  ci/unit_tests/functions_deploy/main_data/exampleFunctions.cfg
  ci/unit_tests/functions_deploy/main_data/example_functions/exampleGo.go
  ci/unit_tests/functions_deploy/main_data/example_functions/exampleJavaScript.js
  ci/unit_tests/functions_deploy/main_data/example_functions/examplePHP.php
  ci/unit_tests/functions_deploy/main_data/example_functions/examplePython.py
  ci/unit_tests/functions_deploy/main_data/example_functions/exampleRuby.rb
  ci/unit_tests/functions_deploy/main_data/example_functions/exampleSwift.swift
  ci/unit_tests/functions_deploy/main_data/python2Functions.cfg
  ci/unit_tests/functions_deploy/main_data/python3Functions.cfg
  ci/unit_tests/functions_deploy/main_data/python_version_functions/getPythonMajorVersion.py
  ci/unit_tests/functions_deploy/main_data/zip_functions/__init__.py
  ci/unit_tests/functions_deploy/main_data/zip_functions/__main__.py
  ci/unit_tests/functions_deploy/main_data/zip_functions/helper.py
  ci/unit_tests/functions_deploy/main_test.py
  ci/unit_tests/wawCommons/absoluteFilePaths_test.py
  ci/unit_tests/wawCommons/getFilesAtPath_test.py
  scripts/functions_deploy.py
Labels: Priority: medium, customer request

#273 Fix typo in doc
  scripts.md
Labels: Priority: medium, bug, documentation

#276 I258 fix generating junit xml
  ci/app_tests/generateAndTestWorkspace_data/test_dummy.test
  ci/app_tests/generateAndTestWorkspace_test.py
  scripts/evaluate_tests.py
Labels: CI, Priority: medium, bug, customer request
