Repository IBM/watson-assistant-workbench, pull requests merged in 2019-05, with the labels that each got.

#337 I318 Setup nightly build tests
  ci/unit_tests/functions_delete_package/main_test.py
  ci/unit_tests/functions_deploy/main_test.py
  ci/unit_tests/functions_test/main_test.py
  ci/unit_tests/workspace_delete/main_test.py
Labels: CI, Priority: high

#335 I331 regex cf package delete
  ci/unit_tests/functions_delete_package/main_test.py
  scripts/functions_delete_package.py
  scripts/wawCommons.py
Labels: Priority: medium, functions

#340 I339 add tests setup to README
  README.md
Labels: Priority: medium, documentation

#341 I319 set logger config in tests
  ci/pytest.ini
  scripts/logging_config.ini
  scripts/wawCommons.py
Labels: Priority: medium

#345 [#343] hotfix for pytest default logging change
  requirements_dev.txt
Labels: CI, Priority: high, bug

#349 Updated Readme with header logo & section titles
  README.md
Labels: Priority: low, documentation, enhancement

#358 [#357] Add support for marking test that can fail
  .travis.yml
  ci/conftest.py
  ci/pytest_customization/__init__.py
  ci/pytest_customization/skipiffails_test.py
  ci/unit_tests/functions_deploy/main_test.py
Labels: CI, Priority: high, enhancement

#355 I298 unify calling cf
  ci/unit_tests/functions_deploy/main_test.py
  scripts/functions_test.py
  scripts/wawCommons.py
Labels: CI, Priority: medium, functions, testing

#350 I29 change default values for workspace name and description and add tests
  ci/unit_tests/workspace_compose/__init__.py
  ci/unit_tests/workspace_compose/main_data/dialog.json
  ci/unit_tests/workspace_compose/main_data/entities.json
  ci/unit_tests/workspace_compose/main_data/intents.json
  ci/unit_tests/workspace_compose/main_data/skill_with_all_info.json
  ci/unit_tests/workspace_compose/main_data/skill_without_name_and_description.json
  ci/unit_tests/workspace_compose/main_test.py
  ci/unit_tests/workspace_deploy/__init__.py
  ci/unit_tests/workspace_deploy/main_data/skill_with_name_and_description.json
  ci/unit_tests/workspace_deploy/main_data/skill_without_name_and_description.json
  ci/unit_tests/workspace_deploy/main_test.py
  scripts/workspace_compose.py
Labels: Priority: medium, documentation

#363 [#362] Mark cf seq upload as skipiffails
  ci/unit_tests/functions_deploy/main_test.py
Labels: CI, Priority: high

#352 [#202] Add basic tests for boolean conversion
  ci/unit_tests/dialog_json2xml/main_data/expectedBoolValid.xml
  ci/unit_tests/dialog_json2xml/main_data/inputBoolValid.json
  ci/unit_tests/dialog_json2xml/main_test.py
  ci/unit_tests/dialog_xml2json/main_data/expectedBoolValid.json
  ci/unit_tests/dialog_xml2json/main_data/inputBoolValid.xml
  ci/unit_tests/dialog_xml2json/main_test.py
Labels: Priority: high

#342 I156 Add entity section to cfg, fuzzy settings in csv->json
  ci/unit_tests/entities_csv2json/__init__.py
  ci/unit_tests/entities_csv2json/main_data/fuzzyMatching/fuzzyOffExpected.json
  ci/unit_tests/entities_csv2json/main_data/fuzzyMatching/fuzzyOnExpected.json
  ci/unit_tests/entities_csv2json/main_data/fuzzyMatching/input/basicEntity1.csv
  ci/unit_tests/entities_csv2json/main_data/fuzzyMatching/input/basicEntity2.csv
  ci/unit_tests/entities_csv2json/main_data/fuzzyOff.cfg
  ci/unit_tests/entities_csv2json/main_data/fuzzyOffEmpty.cfg
  ci/unit_tests/entities_csv2json/main_data/fuzzyOn.cfg
  ci/unit_tests/entities_csv2json/main_test.py
  doc/WAW_entities_doc.md
  example/cz_app/common.cfg
  example/en_app/common.cfg
  scripts/entities_csv2json.py
Labels: Priority: medium, entities

#360 I77 better xml validation errors
  ci/unit_tests/dialog_xml2json/main_data/dummyImportXml.xml
  ci/unit_tests/dialog_xml2json/main_data/inputMissingImport.xml
  ci/unit_tests/dialog_xml2json/main_data/invalidInputsAccordingToSchema/autogenerate_typeInvalid.xml
  ci/unit_tests/dialog_xml2json/main_data/invalidInputsAccordingToSchema/goto_targetInvalid.xml
  ci/unit_tests/dialog_xml2json/main_data/invalidInputsAccordingToSchema/node_attributeInvalid.xml
  ci/unit_tests/dialog_xml2json/main_data/invalidInputsAccordingToSchema/node_singleElementInvalid.xml
  ci/unit_tests/dialog_xml2json/main_data/invalidInputsAccordingToSchema/nodes_subElementsInvalid.xml
  ci/unit_tests/dialog_xml2json/main_data/validInputsAccordingToSchema/autogenerate_typeValid.xml
  ci/unit_tests/dialog_xml2json/main_data/validInputsAccordingToSchema/goto_targetValid.xml
  ci/unit_tests/dialog_xml2json/main_data/validInputsAccordingToSchema/node_attributeValid.xml
  ci/unit_tests/dialog_xml2json/main_data/validInputsAccordingToSchema/node_singleElementValid.xml
  ci/unit_tests/dialog_xml2json/main_data/validInputsAccordingToSchema/nodes_subElementsValid.xml
  ci/unit_tests/dialog_xml2json/main_test.py
  scripts/dialog_xml2json.py
Labels: Priority: medium, XML

#366 I294 functions junit xml
  ci/app_tests/testAndEvaluateFunction_test.py
  ci/test_utils.py
  ci/unit_tests/functions_test/_functions_test_v1/main_test.py
  ci/unit_tests/functions_test/_functions_test_v2/main_test.py
  ci/unit_tests/functions_test_evaluate/main_data/test_multi_junitxml.out.json
  ci/unit_tests/functions_test_evaluate/main_data/test_multi_junitxml_ref.eval.junit.xml
  ci/unit_tests/functions_test_evaluate/main_test.py
  doc/WAW_functions_doc.md
  scripts/ExceptionCommons.py
  scripts/_functions_test_v1.py
  scripts/_functions_test_v2.py
  scripts/functions_test_evaluate.py
  scripts/wawCommons.py
Labels: CI, Priority: high, functions, testing

#356 I354 rewrite xml structure documentation
  doc/WAW_dialog_doc.md
  doc/WAW_dialog_doc.txt
  doc/WAW_dialog_structure.md
Labels: Priority: low, documentation
