Repository IBM/watson-assistant-workbench, pull requests merged in 2019-04, with the labels that each got.

#283 I230 testing cloud functions
  ci/test_utils.py
  ci/unit_tests/compare_dialogs/main_test.py
  ci/unit_tests/functions_test/__init__.py
  ci/unit_tests/functions_test/main_data/empty_dict.json
  ci/unit_tests/functions_test/main_data/no.json
  ci/unit_tests/functions_test/main_data/test_multi.json
  ci/unit_tests/functions_test/main_data/test_single_all_in_file.json
  ci/unit_tests/functions_test/main_data/test_single_all_in_file_bad_type.json
  ci/unit_tests/functions_test/main_data/test_single_all_in_file_failed.json
  ci/unit_tests/functions_test/main_data/test_single_all_in_file_override_function.json
  ci/unit_tests/functions_test/main_data/test_single_all_in_file_override_package.json
  ci/unit_tests/functions_test/main_data/test_single_invalid.json
  ci/unit_tests/functions_test/main_data/test_single_payload.json
  ci/unit_tests/functions_test/main_data/test_single_payloads_out.json
  ci/unit_tests/functions_test/main_data/test_single_payloads_out_no_json_input.json
  ci/unit_tests/functions_test/main_data/test_single_payloads_out_no_json_output.json
  ci/unit_tests/functions_test/main_data/test_single_payloads_out_non_existing_input.json
  ci/unit_tests/functions_test/main_data/test_single_payloads_out_non_existing_output.json
  ci/unit_tests/functions_test/main_test.py
  scripts/functions_test.py
Labels: CI, Priority: high, customer request, testing

#288 [#287] Change os.system() calls to module.main(args)
  scripts/clean_generated.py
  scripts/update_all.py
Labels: Priority: low

#282 I211 deploy by name doc and parameter function
  scripts/wawCommons.py
  scripts/workspace_deploy.py
Labels: Priority: medium, documentation

#286 HOT FIX: Remove code that prints credentials in workspace_test.py
  scripts/workspace_test.py
Labels: Priority: high, customer request

#281 [#122] add documentation for updated goto node
  doc/WAW_dialog_doc.txt
Labels: Priority: low, documentation

#285 I79 add documentation of logging
  README.md
  logging.md
Labels: Priority: low, documentation

#290 Fix link in T2C doc
  doc/T2C_doc.md
Labels: Priority: low, documentation

#292 I145 release notes v12
  release_notes.md
Labels: Priority: high, T2C, XML, documentation

#284 I172 python3 rewrite
  .travis.yml
  ci/app_tests/generateAndTestWorkspace_test.py
  ci/test_utils.py
  ci/unit_tests/compare_dialogs/main_test.py
  ci/unit_tests/functions_deploy/main_test.py
  ci/unit_tests/functions_test/main_test.py
  ci/unit_tests/workspace_addjson/main_test.py
  scripts/DialogData.py
  scripts/XLSXHandler.py
  scripts/XMLHandler.py
  scripts/cfgCommons.py
  scripts/dialog_code2text.py
  scripts/dialog_json2xml.py
  scripts/dialog_text2code.py
  scripts/dialog_xls2xml.py
  scripts/dialog_xml2json.py
  scripts/entities_csv2json.py
  scripts/entities_csv2nlu.py
  scripts/entities_json2csv.py
  scripts/evaluate_tests.py
  scripts/functions_deploy.py
  scripts/functions_test.py
  scripts/intents_csv2json.py
  scripts/intents_csv2nlu.py
  scripts/intents_json2csv.py
  scripts/wawCommons.py
  scripts/workspace_compose.py
  scripts/workspace_decompose.py
  scripts/workspace_delete.py
  scripts/workspace_deploy.py
  scripts/workspace_test.py
Labels: Priority: medium

#317 I308 workspace delete by name
  ci/app_tests/generateAndTestWorkspace_test.py
  ci/unit_tests/workspace_delete/__init__.py
  ci/unit_tests/workspace_delete/main_data/.gitignore
  ci/unit_tests/workspace_delete/main_data/sample-skill.json
  ci/unit_tests/workspace_delete/main_test.py
  scripts/cfgCommons.py
  scripts/wawCommons.py
  scripts/workspace_delete.py
  scripts/workspace_deploy.py
  scripts/workspace_test.py
Labels: CI, Priority: high, customer request, enhancement

#314 I306 cf delete package script
  ci/test_utils.py
  ci/unit_tests/functions_delete_package/__init__.py
  ci/unit_tests/functions_delete_package/main_data/exampleFunctions.cfg
  ci/unit_tests/functions_delete_package/main_data/exampleFunctionsEmpty.cfg
  ci/unit_tests/functions_delete_package/main_data/example_functions/example1.py
  ci/unit_tests/functions_delete_package/main_data/example_functions/example2.py
  ci/unit_tests/functions_delete_package/main_test.py
  scripts/functions_delete_package.py
  scripts/logging_config.ini
  scripts/wawCommons.py
Labels: Priority: high, customer request, enhancement, functions

#320 I217 update xml schema
  ci/unit_tests/dialog_json2xml/__init__.py
  ci/unit_tests/dialog_json2xml/main_data/expectedActionsValid.xml
  ci/unit_tests/dialog_json2xml/main_data/inputActionsValid.json
  ci/unit_tests/dialog_json2xml/main_test.py
  ci/unit_tests/dialog_xml2json/__init__.py
  ci/unit_tests/dialog_xml2json/main_data/expectedActionsValid.json
  ci/unit_tests/dialog_xml2json/main_data/inputActionsValid.xml
  ci/unit_tests/dialog_xml2json/main_test.py
  data_spec/dialog_schema.xml
  doc/WAW_dialog_doc.txt
  scripts/dialog_xml2json.py
Labels: CI, Priority: medium, dialog, documentation

#325 [#308] add tests and message for deleting workspaces
  ci/unit_tests/workspace_delete/main_test.py
  scripts/wawCommons.py
  scripts/workspace_delete.py
Labels: CI, Priority: medium, dialog

#329 I302 tags order
  ci/app_tests/convertWorkspaceBackAndForth_test.py
  ci/unit_tests/dialog_json2xml/main_test.py
  ci/unit_tests/dialog_xml2json/main_test.py
  scripts/dialog_xml2json.py
Labels: Priority: high, XML, bug, dialog

#328 I327 Support python version 3.5
  .travis.yml
  README.md
  ci/unit_tests/functions_delete_package/main_test.py
  scripts/functions_delete_package.py
  scripts/workspace_delete.py
Labels: Priority: high, customer request

#333 I321 cf deploy sequence
  ci/unit_tests/functions_delete_package/main_test.py
  ci/unit_tests/functions_deploy/main_data/exampleNonexistentFunctionRef.cfg
  ci/unit_tests/functions_deploy/main_data/exampleUndefinedSequence.cfg
  ci/unit_tests/functions_deploy/main_data/exampleValidSequences.cfg
  ci/unit_tests/functions_deploy/main_data/example_functions_seq/example1.py
  ci/unit_tests/functions_deploy/main_data/example_functions_seq/example2.py
  ci/unit_tests/functions_deploy/main_data/example_functions_seq/example3.py
  ci/unit_tests/functions_deploy/main_test.py
  scripts/functions_delete_package.py
  scripts/functions_deploy.py
Labels: Priority: medium

#332 I302 tags order PR comments fix
  scripts/dialog_xml2json.py
Labels: Priority: low

#334 I330 Release notes for 2.1. release
  release_notes.md
Labels: Priority: medium, documentation
